/**
 * Theme JS
 *
 * All the theme specific js
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

jQuery(document).ready(function($) {
    //doesn't wait for images, style sheets etc..
    //is called after the DOM has been initialized

    //set up vars
    var sec_menu = 'second_menu';
    var slider = 'slider_lite_section';

    //loop through each full width conatiner
    $(".container-full-width").each(function(i) {
        if (i == 1 || i == 2 || i == 3) {
            if($(this).attr('id') == sec_menu || ($(this).attr('id')) == slider) {
                $(this).css('margin-top', '-40px');
            }
        }
    })
});